Incorporate workflow building t-network solidity-contracts
keep-network/ci pull request #24
Opened 2022-01-28 14:35 UTC by michalinacienciala

We're adding a new module (`threshold-network/solidity-contracts`) to
the CI flow configuration. As the module should be built before
`tbtc-v2` and `coverage-pools` modules and will be changed more often
than `tbtc`, it's placed between `tbtc` and `tbtc-v2` in the CI flow.
Apart from changing the `config.json file, we're also updating actions
which rely on this file.

TODO after merging:
[ ] update the v1 tag

2022-01-28 15:07 UTC, michalinacienciala commented
Now that I think about it, we probably need to do some additional, more complex changes in the actions, because the workflow we're adding to the CI flow belongs to a different organization than the `ci` project (`threshold-network` vs `keep-network`) and we will not be able to authorize triggering of the workflow in `threshold-network` using `keep-network`'s `GITHUB_TOKEN`.
@nkuba, do you think would it be possible to add a `threshold-network`'s token as a secret in `keep-network` and modify code of our actions to support differentiation between the tokens for `threshold-network` and `keep-network`?

2022-01-31 16:32 UTC, michalinacienciala commented
I discussed the issue with @Kuba. We substitute `GITHUB_TOKEN` with `CI_GITHUB_TOKEN`, which is a token for `thesis-heimdall` user. We should be able to trigger `threshold-network` workflows from `keep-core/ci` repo if `thesis-heimdall` user gets added as a member of `threshold-network` organization - this needs to be done by @pdyraga.

2022-02-07 09:57 UTC, nkuba requested changes

2022-02-07 09:57 UTC, nkuba commented on actions/notify-workflow-completed/dist/ceda2c0264ac98da5d36.json
> +    "defaultModule": "github.com/keep-network/keep-core/solidity",
Those generated files look incorrect, aren't they out of sync with the actual source code?

2022-02-08 14:04 UTC, michalinacienciala commented
@nkuba, I looked at your change (e609f35b65f84cb04cb068eb5f268a52aa18a738), looks ok to me. Once you review my changes, we should be ready to merge. After the merge I will update the tag for the actions

2022-02-09 11:37 UTC, nkuba approved these changes

2022-02-09 11:37 UTC, merged